version: '3.8'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root


  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      - DB_HOST=db

  frontend:
    container_name: nginx
    restart: always
    build: ./frontend
    ports:
      - 8090:80
    # volumes:
    #     - ${APPLICATION}:/var/www/html
    #     - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
    #     - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
    # ports:
    #     - "${NGINX_HOST_HTTP_PORT}:80"
    #     - "${NGINX_HOST_HTTPS_PORT}:443"