version: '3.8'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root


  backend:
    build: .
    depends_on:
      - db
    #command: python manage.py run -h 0.0.0.0
    # volumes:
    #   - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      - DB_HOST=db
    #   - FLASK_ENV=development
    #   - SECRET_KEY=9OLWxND4o83j4Kty567pO
    #   - FLASK_RUN_PORT=5000
    #   - DATABASE_URL=postgresql://pstgr_user:pstgr_pass@dbcont:5432/pstgr_db
    #   - REDIS_URL=redis://rediscont:6379
    #   - APP_FOLDER=/usr/src/app
    #   #Used for entrypoint.sh while waiting postgre container is ready
    #   - SQL_HOST=dbcont
    #   - SQL_PORT=5432
    #   - DATABASE=postgres

# volumes:
#   sqlite-data: